export enum DTwenty {
    build_cat = 'Additional Feature',
    'Built around Holy site/Magical Power Source' = 1,
    'Defensive structure (Barracks, strategic location, gatehouse, fort, etc.)' = 2,
    'Wizard’s Tower (Active, Abandoned)' = 3,
    'Church/Shrine/Temple' = 4,
    'Tended Gardens' = 5,
    'Ruins (Castle, Cathedral, Shipyards)' = 6,
    'Sealed Cave/Subterranean Entrance' = 7,
    'Unsealed Cave/Subterranean Entrance' = 8,
    'Lighthouse or Watchtower' = 9,
    'Library/Knowledge Repository' = 10,
    'Crossroads/Major Road/Bridge' = 11,
    'Harbor/Bay' = 12,
    'Skirmish Aftermath (Neighboring Town, Invading Horde, Rampaging Beast)' = 13,
    'Spiritual Lodge (Monastery, etc.)' = 14,
    'Public Punishment Feature (Stocks, Chopping Block, Gallows, etc.)' = 15,
    'Graveyard, Tombs, etc.' = 16,
    'A River Runs Through It' = 17,
    'Built into a Hill- or Mountain-Side' = 18,
    'Built into a Canyon or Ravine' = 19,
    'Built in Forest/Wilderness' = 20
}
